# Alembic Configuration

# The genesis package is where the migration script is located by default
script_location = alembic

# The output encoding used to write the migration file as well as the main configuration file
output_encoding = utf-8

# Version of the SQLAlchemy connection string used by the migration script
# When using this to connect to the database, sqlalchemy.engine.Engine will be used
# If you want to pass additional arguments to engine.create, this is the place to do it
# set your database connection url here
sqlalchemy.url = driver://user:password@localhost/dbname

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
